config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, only: [:index, :new, :create, :show, :destroy]
  resources :events, only: [:index, :new, :create, :show, :destroy]
  get 'signup', to: 'users#new'
  resources :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :attendee, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event, class_name: 'Event'
  belongs_to :user, class_name: 'User'

  validates_uniqueness_of :user, scope: :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :date, presence: true
  validates :location, presence: true

  belongs_to :user
  has_many :attendees
  has_many :user_attendee, through: :attendees, source: :user

  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.username = username.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

  has_many :events
  has_many :attendees
  has_many :attended_events, through: :attendees, source: :event

  has_many :authored_events, foreign_key: 'user_id', class_name: 'Event'

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ? ', Date.today) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
end

app/controllers/attendee_controller.rb
class AttendeeController < ApplicationController
  def create
    @attendee = Attendee.new(attendee_params)
    if @attendee.save
      redirect_to user_path(current_user.id)
    # redirect_back(fallback_location: event_path(attendee_params[:event_id]))
    else
      flash[:notice] = 'You are already attending'
      redirect_to events_path
    end
  end

  def destroy
    @attendee = Attendee.find_by(user_id: attendee_params[:user_id])
    redirect_to user_path(current_user) if @attendee.destroy
  end

  private

  def attendee_params
    params.require(:attendee).permit(:user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show destroy]
  before_action :require_user, except: %i[show index]

  def show
    @attendee = Attendee.new
    @events_past = Event.past.order('datetime DESC')
    @events_future = Event.upcoming.order('datetime ASC')
  end

  def index
    @upcoming = Event.upcoming.sort { |a, b| b.date <=> a.date }
    @past = Event.past.sort { |a, b| b.date <=> a.date }
    @all_events = Event.all
    @attendee = Attendee.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.user = current_user
    if @event.save
      flash[:notice] = 'Event was created succesfully'
      redirect_to events_path
    else
      render 'new'
    end
  end

  def destroy
    @event.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user
      session[:user_id] = user.id
      flash[:notice] = "Welcome #{user.username}, to private events"
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = 'Failed to login. User not register'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @created_events = current_user.events
    @user = User.find(params[:id])
    @upcoming = @user.attended_events.upcoming
    @past = @user.attended_events.past
    @my_events = @user.attended_events
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, to private events"
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attendance_user(user, event)
    return render inline: "<%= link_to 'Login to assist', login_path%>" unless logged_in?

    if Attendee.where(user_id: user, event_id: event).any?
      render '/events/unattendEvent'
    else
      render '/events/attendEvent'
    end
  end

  def attendance_show(event)
    return render inline: "<%= link_to 'Login to assist', login_path%>" unless logged_in?

    if Attendee.where(user_id: current_user[:id], event_id: event).any?
      render inline: 'Attend'
    else
      render inline: 'UnAtttend'
    end
  end
end

app/views/events/_attendEvent.html.erb
<%= form_with model: @attendee, method: :post, url: attendee_index_path, local: true do |f| %>

<%= f.hidden_field :event_id, :value => params[:id] %>
<%= f.hidden_field :user_id, :value => current_user.id %>

<%= f.submit "Attend", class: "px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"%>

<% end %>

app/views/events/_form.html.erb
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
      <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
        Create a new event
      </h2>
    </div>

    <% if @event.errors.any? %>
    <div class="bg-yellow-200 p-5 text-gray-500">
      <span class="closebtn font-extrabold text-3xl" onclick="this.parentElement.style.display='none';">&times;</span>
      <p class="text-red-500">Cannot create event because:</p>
      <ul class="ml-8">
        <% @event.errors.full_messages.each do |msg| %>
        <li class="list-disc"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_with scope: :event, url: events_path, local: true, html: { class: "event-form" } do |f| %>
      
      <div class="rounded-md shadow-sm -space-y-px mb-9">
      <div>
      <%= f.label :title, id: 'title', class: "sr-only" %><br>
      <%= f.text_field :title, id: 'title', class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "Event Title" %>
      </div>
      <div>
      <%= f.label :date, class: "sr-only" %><br>
      <%= f.datetime_field :date, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "Event Date"%>
  </div>
  <div>
      <%= f.label :location, class: "sr-only" %><br>
      <%= f.text_field :location, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "Location" %>
  </div>
</div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <!-- Heroicon name: lock-closed -->
            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
            </svg>
          </span>
          Create
        </button>
      </div>
      <% end %>
      <button type="submit"
      class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-red-500 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">

      <%= link_to 'Cancel and return to event listing', events_path %>
    </button>
  </div>
</div>

app/views/events/_unattendEvent.html.erb
Not attend
<% if false %>
     form_with model: @attendee, method: :delete, url: attendee_path do |f| %>

    <%= f.hidden_field :event_id, :value => params[:id] %>
    <%= f.hidden_field :user_id, :value => current_user[:id] %>
    
    <%= f.submit "Not Attend", class: "px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"%>
    
<% end %>

app/views/events/index.html.erb
<img class="mx-auto h-12 w-auto mt-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
  alt="Workflow">

<h2 class="mt-6 mb-9 text-center text-3xl font-extrabold text-gray-900">
  Future Events
</h2>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                HOST
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                EVENT
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                LOCATION
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @upcoming.each do |event| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div>
                    <div class="text-sm text-green-700">
                      <p class="font-extrabold"><%= event.user.username.upcase %></p>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= event.date %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= event.title %></div>
                <div class="text-sm text-gray-500">Attendees: </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= event.location %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <p class="text-indigo-600 hover:text-indigo-900">
                  <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <p class="text-indigo-600 hover:text-indigo-900">
                  <%= link_to 'View Event', event_path(event)%></p>
                <p><%= attendance_user(current_user, event) %></p>
              </td>
            </tr>
            
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <h2 class="mt-6 mb-9 text-center text-3xl font-extrabold text-gray-500">
  Past Events
</h2>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                HOST
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                EVENT
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                LOCATION
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @past.each do |event| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div>
                    <div class="text-sm text-green-400">
                      <p class="font-extrabold"><%= event.user.username.upcase %></p>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= event.date %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-400"><%= event.title %></div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= event.location %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <p class="text-indigo-400 hover:text-indigo-600">
                  <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <p class="text-indigo-400 hover:text-indigo-600">
                  <%= link_to 'View Event', event_path(event)%></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</div>

app/views/events/new.html.erb
<% if logged_in? %>
<%= render 'form' %>
<% else %>
<%controller.redirect_to login_path %>
<% end %>

app/views/layouts/_nav.html.erb
<div>
  <nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
          </div>
          <div>
            <div class="ml-10 flex items-baseline space-x-4">
              <p class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                <%= link_to 'Home', root_path %>
              </p>

              <p class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                <%= link_to 'All events', events_path %>
              </p>

              <p class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                <%= link_to 'New Event', new_event_path %>
              </p>
              
              <% if logged_in? %>  
              <p class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
              <%= link_to 'My Events', user_path(current_user) %>
              </p>
              <% end %>

            </div>
          </div>
        </div>
        <div>
          <div class="ml-4 flex items-center md:ml-6">
            <% if logged_in? %>
            <p class="bg-gray-900 text-white mr-3 px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"">
                        <%= link_to 'Log Out', logout_path, method: :delete %> 
                        </p>
                        <p class=" bg-gray-800 p-1 text-gray-400">
              <!-- Heroicon name: user -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            </p>
            <p class="text-gray-300 text-lg">
              Signed as: <span class="font-bold text-green-500"><%= current_user.username.upcase %></span>
            </p>

            <% else %>
            <p class="text-white mr-3 px-3 py-2 rounded-md text-sm font-medium bg-indigo-600 hover:bg-indigo-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
              <%= link_to 'LOGIN', login_path %>
            </p>
            <p class="bg-gray-900 text-white mr-3 px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
              <%= link_to 'REGISTER', signup_path %>
            </p>
            <% end %>

          </div>
        </div>

      </div>
    </div>


</div>
</nav>
</div>

app/views/users/_attend.html.erb
<%= link_to 'Assist', attendee_index_path(attendee: { user_id: current_user[:id], event_id: event }), 
            method: :post, class: 'badge badge-success' %>

app/views/users/_unattend.html.erb
<%= link_to 'Unassist', attendee_path(attendee: { user_id: current_user[:id], event_id: event.id }), 
            method: :delete, class: 'badge badge-danger' %>

app/views/users/index.html.erb
<img class="mx-auto h-12 w-auto mt-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
  alt="Workflow">
<h2 class="mt-6 mb-9 text-center font-light text-3xl text-gray-900">
<% if logged_in? %> 
  Events for <span class="font-extrabold"><%= current_user.username %></span>
<% else %>
  Please <%= link_to 'Register', signup_path, class: "underline hover:no-underline" %> or <span class="font-extrabold">
  <%= link_to 'Login', login_path, class: "underline hover:no-underline" %></span>
<% end %>

app/views/users/show.html.erb
<img class="mx-auto h-12 w-auto mt-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
  alt="Workflow">
<h2 class="mt-6 mb-9 text-center font-light text-3xl  text-gray-900">
  Events for <span class="font-extrabold"><%= @current_user.username %></span>
</h2>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <button
        class="py-2 px-4 my-6 text-lg bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75">
        <%= link_to 'CREATE A NEW EVENT', new_event_path %>
      </button>
      <h2 class="mt-6 mb-6 text-center text-3xl font-extrabold text-gray-900">
        Events <span class="font-light">created by you</span>
      </h2>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                HOST
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                EVENT
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                LOCATION
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @created_events.each do |event| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div>
                    <div class="text-sm text-green-700">
                      <p class="font-extrabold"><%= event.user.username.upcase %></p>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= event.date %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= event.title %></div>
                <div class="text-sm text-gray-500">Attendees: <%= event.user_attendee.count %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= event.location %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
              <p class="text-red-600 hover:text-red-900">
              <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></p>
              <p class="text-green-600 hover:text-green-900">
              <%= link_to 'Attendees', event_path(event)%></p>
              <p>
                <%= attendance_show(@user.authored_events) %>
                </p>
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>


      <h2 class="mt-12 mb-6 text-center text-3xl font-extrabold text-gray-900">
        Events <span class="font-light">you are going to attend</span>
      </h2>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                HOST
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                EVENT
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                LOCATION
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @my_events.each do |event| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div>
                    <div class="text-sm text-green-700">
                      <p class="font-extrabold"><%= event.user.username.upcase %></p>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= event.date %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= event.title %></div>
                <div class="text-sm text-gray-500">Attendees: <%= event.user_attendee.count %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  <%= event.location %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <p class="text-red-600 hover:text-red-900">
                <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></p>
                <p class="text-green-600 hover:text-green-900">
                <%= link_to 'Attendees', event_path(event)%></p>
                
                <p><%= link_to 'Not Attend', attendee_path(attendee: { user_id: current_user.id, event_id: event.id }),
                method: :delete, class: 'px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800' %></p>
                
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="mt-12 mb-6 text-center text-3xl font-extrabold text-gray-400">
        Events <span class="font-light">you already attended</span>
      </h2>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                HOST
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                EVENT
              </th>
              <th scope="col"
                class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                LOCATION
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @past.each do |event| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div>
                    <div class="text-sm text-green-400">
                      <p class="font-extrabold"><%= event.user.username.upcase %></p>
                    </div>
                    <div class="text-sm text-gray-400">
                      <%= event.date %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-500"><%= event.title %></div>
                <div class="text-sm text-gray-400">Attendees: <%= event.user_attendee.count %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-50 text-green-500">
                  <%= event.location %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <p class="text-indigo-600 hover:text-indigo-900">
                  <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></p>
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>
</div>